import {parseBinding} from '../input/Bindings.js';
export const ACTIONS=Object.freeze({moveForward:'Move forward',moveBackward:'Move backward',moveLeft:'Move left',moveRight:'Move right',jump:'Jump',crouch:'Crouch',sprint:'Sprint',interact:'Interact / loot',reload:'Reload',inventory:'Inventory',flashlight:'Flashlight',map:'Map',favorites:'Favorites',screenshot:'Capture PNG',quicksave:'Quick save',quickload:'Quick load',fire:'Fire',aim:'Aim',steadyAim:'Hold breath while aiming',slot1:'Primary weapon',slot2:'Secondary weapon',slot3:'Melee weapon',quick1:'Quick item 1',quick2:'Quick item 2',quick3:'Quick item 3',quick4:'Quick item 4',throw_bolt:'Throw anomaly probe',toggle_detector:'Anomaly detector',pause:'Pause',leanLeft:'Lean left',leanRight:'Lean right',nextWeapon:'Next weapon',previousWeapon:'Previous weapon'});
export const PRESETS=Object.freeze({low:{renderDistance:300,shadows:false,shadowSize:1024,bloom:false,aa:false,reflectionQuality:'low',particleQuality:'low',vegetationDetail:false},medium:{renderDistance:500,shadows:true,shadowSize:1024,bloom:true,aa:true,reflectionQuality:'medium',particleQuality:'medium',vegetationDetail:true},high:{renderDistance:750,shadows:true,shadowSize:2048,bloom:true,aa:true,reflectionQuality:'high',particleQuality:'high',vegetationDetail:true},ultra:{renderDistance:1000,shadows:true,shadowSize:4096,bloom:true,aa:true,reflectionQuality:'ultra',particleQuality:'ultra',vegetationDetail:true}});
const field=(key,id,category,label,type,defaultValue,help,cost,options={})=>({key,id,category,label,type,defaultValue,help,cost,...options});
const tiers=['low','medium','high','ultra'];
export const SETTINGS_FIELDS=Object.freeze([
field('resolution','set-resolution','Display','Window resolution','select','1600x900','Sets the desktop window content size. Fullscreen uses the display resolution.','More pixels cost GPU time and render-target memory.',{values:['1024x640','1280x720','1600x900','1920x1080'],desktop:true}),
field('fullscreen','set-fullscreen','Display','Borderless fullscreen','boolean',false,'Fill the current display; turn off for windowed play.','Cost follows the resulting pixel count.'),
field('vsync','set-vsync','Display','Vsync','boolean',true,'Synchronize frames with the display. Desktop restart required; the OS may still control presentation.','Off removes frame limiting and can increase GPU use.',{desktop:true}),
field('fov','set-fov','Display','Vertical field of view','range',75,'Wider peripheral view and stronger bodycam perspective. Does not change mouse sensitivity.','Wider views can expose more geometry.',{min:60,max:110,step:1,unit:'°'}),
field('showFps','set-show-fps','Display','Show FPS','boolean',false,'Show the small frame-rate readout; F3 offers detailed diagnostics.','Negligible display cost.'),
field('quality','set-quality','Graphics','Preset','select','medium','Set a coherent detail baseline. Advanced controls can then override it.','Higher tiers increase pixel, shadow, reflection and effect work.',{values:tiers}),
field('autoQuality','set-auto-quality','Graphics','Automatic render scale','boolean',true,'The current governor adjusts internal resolution between 50% and your scale ceiling.','Reduces pixel cost when frames are slow.'),
field('renderScale','set-render-scale','Graphics','Render scale ceiling','range',100,'Internal resolution relative to window/display size. HUD text stays at native size.','Pixel work scales approximately with the square of this value.',{min:50,max:100,step:5,unit:'%'}),
field('renderDistance','set-render-distance','Graphics','View distance','range',500,'Set how far you can see. This does not unload city physics or simulation.','More distant visible surfaces can cost CPU/GPU work.',{min:200,max:1000,step:50,unit:'m',advanced:true}),
field('shadows','set-shadows','Graphics','Dynamic shadows','boolean',true,'Enable sun, moon and flashlight shadow maps.','Extra scene passes and shadow-map memory.',{advanced:true}),
field('shadowSize','set-shadow-size','Graphics','Shadow map size','select',1024,'Control shadow texture resolution; available when shadows are on.','Memory grows quadratically; 4096 is costly.',{values:[1024,2048,4096],advanced:true}),
field('reflectionQuality','set-reflections','Graphics','Reflection detail','select','medium','Change local probe size, capture range, puddle resolution and refresh interval.','Higher tiers render more reflection pixels more often.',{values:tiers,advanced:true}),
field('vegetationDetail','set-vegetation','Graphics','Detailed canopy','boolean',true,'Show additional near-field canopy planes. Tree placement and collision stay consistent.','Additional foliage draw and alpha-shading work.',{advanced:true}),
field('particleQuality','set-particles','Graphics','Particle capacity','select','medium','Allow more cosmetic impact/explosion particles; changing it clears current bursts.','Higher caps increase effect buffers and drawing. Destruction bodies are unaffected.',{values:tiers,advanced:true}),
field('post','set-post','Graphics','Post effects','boolean',true,'Enable the bodycam post-processing chain. Individual effects below depend on it.','Additional full-screen work.',{advanced:true}),
field('ambientOcclusion','set-ao','Graphics','Contact occlusion','boolean',false,'Depth-based occlusion on static and moving surfaces. Automatic quality can suspend it under pressure.','A half-resolution GTAO pass; full-city cost unverified.',{advanced:true}),
field('lensDirt','set-lens-dirt','Graphics','Lens dirt','boolean',true,'Subtle glare-linked lens smudges; disabled with lens effects.','Small full-screen shader work.',{advanced:true}),
field('rollingShutter','set-rolling-shutter','Graphics','Rolling shutter','boolean',false,'Tiny movement-linked image skew. Full camera-motion disable also disables it.','Extra scene texture sampling.',{advanced:true}),
field('bloom','set-bloom','Graphics','Bloom','boolean',true,'Glow around bright sources.','Extra filtered image passes.',{advanced:true}),
field('aa','set-aa','Graphics','Edge smoothing','boolean',true,'FXAA smoothing of rendered edges.','One full-screen filtering stage.',{advanced:true}),
field('grain','set-grain','Graphics','Film grain / low-light noise','boolean',true,'Animated camera texture with extra noise in deep shadows; presets retain it for the bodycam aesthetic.','Small shader cost.',{advanced:true}),
field('vignette','set-vignette','Graphics','Vignette','boolean',true,'Darken screen edges; disable for visibility or comfort.','Small shader cost.',{advanced:true}),
field('chroma','set-chroma','Graphics','Color fringing','boolean',false,'Offset color channels at the image edges; optional for visual comfort.','Additional shader samples.',{advanced:true}),
field('masterVolume','set-master-volume','Audio','Master volume','range',100,'Scale every game audio category, including sounds already playing.','Tiny audio cost.',{min:0,max:100,step:1,unit:'%'}),
field('musicVolume','set-music-volume','Audio','Music volume','range',50,'Scale procedural ambient music independently.','Negligible; zero volume does not unload the synthesizer.',{min:0,max:100,step:1,unit:'%'}),
field('sfxVolume','set-sfx-volume','Audio','Effects volume','range',80,'Scale weapons, movement, hazards and ambience, including active sounds.','Tiny audio cost.',{min:0,max:100,step:1,unit:'%'}),
field('voiceVolume','set-voice-volume','Audio','Voice / whispers','range',100,'Scale the existing hallucination whispers and any registered voice-category lines.','Tiny audio cost.',{min:0,max:100,step:1,unit:'%'}),
field('subtitles','set-subtitles','Audio','Subtitles & sound captions','boolean',true,'Show supplied voice captions and selected warning cues. Interactive dialogue text is always retained.','Small bounded text overlay.'),
field('dynamicRange','set-dynamic-range','Audio','Dynamic range','select','wide','Wide preserves loud/quiet contrast. Night compresses peaks for quieter listening.','Tiny audio processing cost.',{values:['wide','night']}),
field('sensitivity','set-sensitivity','Controls','Mouse sensitivity','range',50,'Scale pointer movement into camera rotation; smoothing is separately optional and off by default.','Negligible.',{min:1,max:100,step:1}),
field('rawInput','set-raw-input','Controls','Raw mouse input','boolean',true,'Request unadjusted pointer movement at the next click-to-lock. Unsupported systems fall back and report it.','Negligible; support depends on platform.'),
field('mouseCurve','set-mouse-curve','Controls','Mouse response','select','linear','Linear preserves count-for-count response. Precision lowers the gain of slow movements without exceeding base sensitivity.','Tiny input-math cost.',{values:['linear','precision']}),
field('mouseSmoothing','set-mouse-smoothing','Controls','Mouse smoothing','boolean',false,'Optional velocity filtering. Off gives the most direct response; weapon inertia remains visual.','Adds the selected filter delay.'),
field('mouseSmoothingMs','set-mouse-smoothing-ms','Controls','Smoothing time','range',8,'Filter time in milliseconds; used only when smoothing is on.','Longer values increase aiming delay.',{min:5,max:40,step:1,unit:' ms'}),
field('controllerEnabled','set-controller-enabled','Controls','Controller gameplay','boolean',true,'Use standard-mapped Xbox/PlayStation controllers. Menu navigation remains available when gameplay input is off.','One poll per frame.'),
field('controllerLayout','set-controller-layout','Controls','Controller labels','select','auto','Auto detects common device names; choose labels manually when a driver reports a generic controller.','No meaningful cost.',{values:['auto','xbox','playstation']}),
field('controllerSensitivity','set-controller-sensitivity','Controls','Controller turn speed','range',180,'Maximum stick turn speed in degrees per second.','Tiny input-math cost.',{min:60,max:360,step:10,unit:'°/s'}),
field('controllerDeadzone','set-controller-deadzone','Controls','Stick deadzone','range',12,'Radial deadzone for both sticks; increase to suppress drift.','Higher values reduce available fine movement.',{min:5,max:30,step:1,unit:'%'}),
field('controllerCurve','set-controller-curve','Controls','Stick response','select','precision','Precision uses an exponent of 1.6 for finer small stick movements. Linear is proportional.','Tiny input-math cost.',{values:['linear','precision']}),
field('controllerAdsScale','set-controller-ads','Controls','Controller aiming speed','range',55,'Scale stick turn speed while aiming down sights.','No meaningful extra cost.',{min:30,max:100,step:5,unit:'%'}),
field('controllerAimAssist','set-controller-assist','Controls','Controller aim slowdown','range',15,'Up to 25% slowdown near a visible enemy while aiming. No pull, tracking or mouse assistance. Zero disables it.','A bounded visibility check at most ten times per second.',{min:0,max:25,step:5,unit:'%'}),
field('invertX','set-invert-x','Controls','Invert horizontal look','boolean',false,'Reverse horizontal camera movement.','Negligible.'),
field('invertY','set-invert-y','Controls','Invert vertical look','boolean',false,'Reverse vertical camera movement.','Negligible.'),
field('difficulty','set-difficulty','Gameplay','Difficulty','select','standard','Relaxed: 75% incoming damage, 65% survival pressure. Standard: 100%. Harsh: 135% damage, 125% survival pressure. Hazards, scarcity and training rules remain.','No additional simulation workload.',{values:['relaxed','standard','harsh']}),
field('hudOpacity','set-hud-opacity','Gameplay','HUD opacity','range',100,'Fade passive gameplay HUD elements. Menus, dialogue and interaction prompts remain readable.','Tiny interface cost.',{min:0,max:100,step:5,unit:'%'}),
field('cameraMotion','set-camera-motion','Accessibility','Camera bob & shake','range',100,'Scale walking bob, automatic roll, landing and recoil shake. Zero fully disables involuntary camera motion; deliberate leaning still changes viewpoint.','No extra render pass.',{min:0,max:100,step:5,unit:'%'}),
field('weaponMotion','set-weapon-motion','Accessibility','Weapon idle motion','range',100,'Scale weapon bob, breathing, look sway and visual kick. Zero keeps the weapon steady; reload and handling actions remain visible.','No extra render pass.',{min:0,max:100,step:5,unit:'%'}),
field('lensEffects','set-lens-effects','Accessibility','Decorative lens effects','boolean',true,'Allow bloom, vignette and color fringing selected in Graphics. Turn off to bypass all three; film grain has its own Graphics toggle.','Off reduces post-processing work.'),
field('anomalyPalette','set-anomaly-palette','Accessibility','Anomaly palette','select','universal','Distinct universal hues plus field shapes and detector labels. Monochrome uses white with the same shapes and labels.','Applied when settings or fields change.',{values:['universal','monochrome']}),
field('highContrast','set-high-contrast','Accessibility','High-contrast interface','boolean',false,'Opaque dark panels, bright text and strong focus outlines, including gameplay prompts.','Small interface cost.'),
field('subtitleSize','set-subtitle-size','Accessibility','Subtitle size','range',22,'Caption and critical sound-cue text size. Dialogue text follows this size as well.','Small interface layout cost.',{min:16,max:36,step:2,unit:'px'}),
field('subtitleBackground','set-subtitle-background','Accessibility','Subtitle background','range',90,'Caption and critical sound-cue background opacity. Use 100 for a solid background.','Small interface cost.',{min:0,max:100,step:5,unit:'%'}),
field('visualAudioCues','set-visual-audio','Accessibility','Critical sound indicators','boolean',true,'Show sirens, creature growls and electrical/detector cues visually even when sound or subtitles are off. Directions use actual sound sources; no enemy markers.','Up to three brief text cues.'),
field('monoAudio','set-mono-audio','Accessibility','Mono audio','boolean',false,'Downmix the final game audio mix to mono and send the same mix to both channels. Positional attenuation remains; stereo direction is lost.','One small Web Audio mixing node.'),
field('damageNumbers','set-damage-numbers','Gameplay','Damage readout','boolean',false,'Optional brief readout for your confirmed hits; off by default for immersion.','One reused text element.')
]);
export const DEFAULT_SETTINGS=Object.freeze(Object.fromEntries(SETTINGS_FIELDS.map(f=>[f.key,f.defaultValue])));
export function normalizeSettings(raw={}){
    const s={schema:4,accessibilityReviewed:raw?.accessibilityReviewed===true};if(!raw||typeof raw!=='object')raw={};if(raw.schema!==4&&Object.hasOwn(PRESETS,raw.quality))raw={...PRESETS[raw.quality],...raw};
    for(const f of SETTINGS_FIELDS){const v=raw[f.key];s[f.key]=f.type==='boolean'?typeof v==='boolean'?v:f.defaultValue:f.type==='range'?Number.isFinite(v)?Math.min(f.max,Math.max(f.min,Math.round(v/f.step)*f.step)):f.defaultValue:f.values.includes(v)?v:f.defaultValue;}
    s.bindings={};for(const [action,keys]of Object.entries(raw.bindings||{}))if(Object.hasOwn(ACTIONS,action)&&Array.isArray(keys))s.bindings[action]=keys.filter(code=>validBinding(code)&&(code!=='Escape'||action==='pause')).map(code=>parseBinding(code).code).slice(0,2);
    if(s.bindings.pause?.length===0)delete s.bindings.pause;return s;
}
export function validBinding(code){return !!parseBinding(code);}
export function applyPreset(settings,quality){return normalizeSettings({...settings,...PRESETS[quality],quality,grain:settings.grain,post:true});}
export function incomingDamage(amount,difficulty,source){return amount*(source?.type==='training'?1:({relaxed:.75,standard:1,harsh:1.35}[difficulty]||1));}
