import * as THREE from 'three';
import {ACHIEVEMENTS} from '../systems/CampaignStatistics.js';
/** Photo camera never moves the actor or advances simulation. */
export class PhotoMode{
 constructor(game){this.game=game;this.active=false;this.busy=false;this.options={aperture:16,focus:10,grain:game.settings.filmGrain?20:0,filter:'bodycam',timestamp:true};this.offset=new THREE.Vector3();this.direction=new THREE.Vector3();this.keys=new Set();
  this.root=document.createElement('div');this.root.id='photo-panel';this.root.className='menu hidden';this.root.innerHTML=`<div class="menu-header"><h2>Dark Rain · Camera</h2></div><div class="menu-content"><p>World paused · camera stays within 10 m. Drag outside the panel to look. WASD move, E/Q up/down.</p><label>Focal length <input data-option="lens" type="range" min="18" max="85" value="24"><output>24 mm</output></label><label>Aperture / depth blur <input data-option="aperture" type="range" min="1.4" max="16" step=".2" value="16"><output>f/16</output></label><label>Focus distance <input data-option="focus" type="range" min=".5" max="60" step=".5" value="10"><output>10 m</output></label><label>Grain <input data-option="grain" type="range" min="0" max="100" value="${this.options.grain}"><output>${this.options.grain}%</output></label><label>Filter <select data-option="filter"><option value="bodycam">Bodycam</option><option value="warm">Warm archive</option><option value="mono">Monochrome</option></select></label><label><input data-option="timestamp" type="checkbox" checked> Recording timestamp</label><p id="photo-status" role="status">PNG contains the scene only.</p></div><div class="menu-actions"><button class="menu-button" id="photo-capture">Capture PNG</button><button class="menu-button" id="photo-back">Back</button></div>`;
  this.stats=document.createElement('div');this.stats.id='statistics-panel';this.stats.className='menu hidden';this.stats.innerHTML='<div class="menu-header"><h2>Expedition statistics</h2></div><div class="menu-content"></div><div class="menu-actions"><button class="menu-button">Back</button></div>';
  document.getElementById('game-container').append(this.root,this.stats);game.uiManager.elements.photoPanel=this.root;game.uiManager.elements.statisticsPanel=this.stats;game.uiManager.menuStates.photo=false;game.uiManager.menuStates.statistics=false;
  this.root.querySelector('#photo-back').onclick=()=>this.close();this.root.querySelector('#photo-capture').onclick=()=>void this.capture();this.stats.querySelector('button').onclick=()=>this.closeStatistics();
  this.root.querySelectorAll('[data-option]').forEach(el=>el.oninput=()=>{const k=el.dataset.option,v=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:Number(el.value);if(k==='lens'){this.camera?.setFocalLength(v);}else this.options[k]=v;const out=el.nextElementSibling;if(out?.tagName==='OUTPUT')out.textContent=k==='lens'?v+' mm':k==='aperture'?'f/'+v:k==='focus'?v+' m':v+'%';});
  this.down=e=>{if(this.active&&!e.target.closest('input,select,button'))this.keys.add(e.code);};this.up=e=>this.keys.delete(e.code);this.blur=()=>this.keys.clear();this.dragStart=e=>{if(this.active&&!e.target.closest('.menu')){this.dragging=true;e.preventDefault();}};this.dragEnd=()=>this.dragging=false;this.drag=e=>{if(this.active&&this.dragging){this.camera.rotation.order='YXZ';this.camera.rotation.y-=e.movementX*.003;this.camera.rotation.x=THREE.MathUtils.clamp(this.camera.rotation.x-e.movementY*.003,-1.5,1.5);}};
  window.addEventListener('keydown',this.down);window.addEventListener('keyup',this.up);window.addEventListener('blur',this.blur);window.addEventListener('pointerdown',this.dragStart);window.addEventListener('pointerup',this.dragEnd);window.addEventListener('pointermove',this.drag);
 }
 show(){if(this.active||this.game.gameState!=='playing'||this.game.isLoading)return;const g=this.game;this.savedCamera=g.camera;this.anchor=g.player.camera.getWorldPosition(new THREE.Vector3());this.camera=g.player.camera.clone();this.camera.position.copy(this.anchor);this.camera.quaternion.copy(g.player.camera.getWorldQuaternion(new THREE.Quaternion()));this.camera.setFocalLength(Number(this.root.querySelector('[data-option="lens"]').value));this.active=true;g.isPaused=true;g.uiManager.openMenu('photo');g.camera=this.camera;g.buildComposer();document.body.classList.add('photo-active');}
 close(){if(!this.active)return;if(this.busy)return;const g=this.game;this.active=false;this.keys.clear();this.dragging=false;document.body.classList.remove('photo-active');g.camera=this.savedCamera;g.buildComposer();g.uiManager.closeMenu('photo',false);g.uiManager.openMenu('pause');g.inputManager.clearHeldInput();}
 update(dt){if(!this.active)return;const k=this.keys;this.direction.set((k.has('KeyD')?1:0)-(k.has('KeyA')?1:0),(k.has('KeyE')?1:0)-(k.has('KeyQ')?1:0),(k.has('KeyS')?1:0)-(k.has('KeyW')?1:0));if(this.direction.lengthSq())this.camera.position.addScaledVector(this.direction.normalize().applyQuaternion(this.camera.quaternion),Math.min(dt,.05)*3);this.offset.copy(this.camera.position).sub(this.anchor).clampLength(0,10);this.camera.position.copy(this.anchor).add(this.offset);this.camera.aspect=this.game.player.camera.aspect;this.camera.updateProjectionMatrix();}
 async capture(){if(this.busy||this.game.gameState!=='playing'||this.game.isLoading)return false;this.busy=true;const button=this.root.querySelector('#photo-capture');button.disabled=true;
  try{this.game.render(true);const source=this.game.renderer.domElement,out=document.createElement('canvas');out.width=source.width;out.height=source.height;const ctx=out.getContext('2d');ctx.drawImage(source,0,0);if(this.active&&this.options.timestamp){ctx.font=Math.max(14,Math.round(out.height*.022))+'px monospace';ctx.fillStyle='#fff';ctx.shadowColor='#000';ctx.shadowBlur=4;ctx.fillText('DR / '+this.recordingTime(),20,out.height-24);}
   const blob=await new Promise(resolve=>out.toBlob(resolve,'image/png'));if(!blob)throw Error('PNG encoding failed');const bytes=new Uint8Array(await blob.arrayBuffer());let location='Downloads';if(window.darkRainDesktop?.capture)location=await window.darkRainDesktop.capture.write(bytes);else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='DarkRain-'+Date.now()+'.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}this.root.querySelector('#photo-status').textContent='Saved: '+location;this.game.uiManager.showNotification('PNG saved: '+location,'success');return {bytes:bytes.length,width:out.width,height:out.height,path:location};
  }catch(error){this.root.querySelector('#photo-status').textContent='Capture failed: '+error.message;this.game.uiManager.showNotification('Capture failed — try again.','danger');return false;}finally{this.busy=false;button.disabled=false;}
 }
 recordingTime(){const seconds=Math.floor(this.game.playTime||0);return 'REC '+String(Math.floor(seconds/3600)).padStart(2,'0')+':'+String(Math.floor(seconds/60)%60).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}
 showStatistics(){const g=this.game;if(g.gameState!=='playing')return;g.uiManager.openMenu('statistics');const d=g.statisticsSystem.data,content=this.stats.querySelector('.menu-content');content.replaceChildren();const add=text=>{const p=document.createElement('p');p.textContent=text;content.append(p);};add('Time survived: '+Math.floor((g.playTime||0)/60)+' min · Distance walked: '+(d.distance/1000).toFixed(2)+' km');add('Buildings collapsed: '+d.buildings.length+' · Emissions survived: '+d.emissions);for(const a of ACHIEVEMENTS)add((d.unlocked[a.id]!==undefined?'✓ ':'○ ')+a.name+' — '+a.condition);add('Faction standing history (latest 64 changes)');for(const e of d.factions.slice().reverse())add(Math.floor(e.time/60)+' min · '+e.faction+' · '+Math.round(e.rep));}
 closeStatistics(){this.game.uiManager.closeMenu('statistics',false);this.game.uiManager.openMenu('pause');}
 dispose(){if(this.active){this.busy=false;this.close();}this.root.remove();this.stats.remove();window.removeEventListener('keydown',this.down);window.removeEventListener('keyup',this.up);window.removeEventListener('blur',this.blur);window.removeEventListener('pointerdown',this.dragStart);window.removeEventListener('pointerup',this.dragEnd);window.removeEventListener('pointermove',this.drag);}
}
