import {comfortSettings,ANOMALY_PALETTE} from '../core/settings/Accessibility.js';
import {eventBinding,parseBinding} from '../core/input/Bindings.js';
import {SETTINGS_FIELDS,ACTIONS,normalizeSettings,applyPreset,validBinding} from '../core/settings/SettingsSchema.js';
export class SettingsMenu {
    constructor(ui){this.ui=ui;this.game=ui.game;this.category='Display';this.build();this.backListener=e=>{if(e.code==='Escape'&&this.game.gameState==='menu'){if(this.ui.activeMenu==='settings')this.ui.closeSettings();else if(this.ui.activeMenu==='controls')this.ui.closeControls();}};document.addEventListener('keydown',this.backListener);}
    build(){
        const root=document.querySelector('#settings-menu .menu-content');root.replaceChildren();const nav=document.createElement('nav');nav.className='settings-tabs';nav.setAttribute('aria-label','Settings categories');root.append(nav);
        for(const category of ['Display','Graphics','Audio','Controls','Gameplay','Accessibility']){const button=document.createElement('button');button.className='menu-button';button.textContent=category;button.onclick=()=>this.show(category);nav.append(button);const section=document.createElement('section');section.dataset.category=category;root.append(section);
            const heading=document.createElement('h3');heading.textContent=category;section.append(heading);let advanced;
            if(category==='Graphics'){advanced=document.createElement('details');advanced.innerHTML='<summary>Advanced graphics</summary>';section.append(advanced);}
            for(const f of SETTINGS_FIELDS.filter(f=>f.category===category)){const row=document.createElement('div');row.className='setting-row';const label=document.createElement('label');label.htmlFor=f.id;label.textContent=f.label;const desc=document.createElement('span');desc.className='setting-desc';desc.textContent=f.help+' Cost: '+f.cost;label.append(desc);const control=document.createElement('div');control.className='setting-control';let input;
                if(f.type==='select'){input=document.createElement('select');for(const value of f.values){const option=document.createElement('option');option.value=value;option.textContent=typeof value==='string'?value.includes('x')?value.replace('x',' × '):value[0].toUpperCase()+value.slice(1):String(value);input.append(option);}}
                else{input=document.createElement('input');input.type=f.type==='boolean'?'checkbox':'range';if(f.type==='range'){input.min=f.min;input.max=f.max;input.step=f.step;}else input.className='toggle';}
                input.id=f.id;control.append(input);if(f.type==='range'){const value=document.createElement('span');value.className='setting-value';value.id=f.id+'-val';control.append(value);input.oninput=()=>{value.textContent=input.value+(f.unit||'');};}
                input.onchange=()=>this.change(f);row.append(label,control);(f.advanced?advanced:section).append(row);
            }
            if(category==='Accessibility'){const note=document.createElement('p');note.textContent='FOV is in Display; film grain and individual lens effects are in Graphics. Captions and dynamic range are in Audio. Pause is always available in single-player gameplay. These preferences stay independent of saves.';section.append(note);const stable=document.createElement('button');stable.className='menu-button';stable.textContent='Use stable-camera preset';stable.onclick=()=>{this.ui.saveStoredSettings(comfortSettings(this.ui.getStoredSettings()));this.ui.applyStoredSettings();this.populate();};section.append(stable);const legend=document.createElement('div');legend.className='anomaly-legend';legend.setAttribute('aria-label','Anomaly identification legend');for(const [type,style]of Object.entries(ANOMALY_PALETTE)){if(type==='unknown')continue;const row=document.createElement('p'),swatch=document.createElement('span');swatch.className='anomaly-swatch';swatch.style.borderColor=style.color;swatch.textContent=style.symbol;row.append(swatch,document.createTextNode(style.label+' · '+style.color));legend.append(row);}section.append(legend);}
            if(category==='Display'){const status=document.createElement('p');status.id='settings-display-status';status.setAttribute('role','status');section.append(status);const restart=document.createElement('button');restart.id='settings-restart';restart.className='menu-button';restart.textContent='Save and restart for Vsync';restart.hidden=true;restart.onclick=()=>this.restart();section.append(restart);}
            if(category==='Controls'){const note=document.createElement('p');note.id='binding-status';note.setAttribute('role','status');note.textContent='Select a binding, then press a key or mouse button. Hold Ctrl, Alt, Shift or Meta for a combination; release a modifier alone to bind it. Esc cancels. Only identical bindings conflict; OS shortcuts may remain unavailable.';section.append(note);const status=document.createElement('p');status.id='controller-status';status.textContent='Connect a standard controller and press a button.';const guide=document.createElement('details');guide.innerHTML='<summary>Controller layout</summary><p>Left stick: move · Right stick: look<br>LT / L2: aim · RT / R2: fire<br>A / Cross: jump · B / Circle: crouch<br>X / Square: reload · Y / Triangle: next weapon<br>LB / L1: lean left · RB / R1: lean right<br>LS / L3: toggle sprint; hold while aiming to hold breath<br>RS / R3: interact<br>D-pad Up: light · Down: inventory · Left: probe · Right: detector<br>View / Create: map · Menu / Options: pause<br>Menus: D-pad/stick to focus, left/right to adjust, A/Cross to select, B/Circle to go back.</p>';const bindings=document.createElement('div');bindings.id='settings-bindings';section.append(status,guide,bindings);}
            if(category==='Display'){const health=document.createElement('p');health.id='performance-health';health.setAttribute('role','status');health.textContent='Play for a few seconds to measure performance.';const report=document.createElement('button');report.id='perf-export-btn';report.className='menu-button';report.textContent='Save performance report';report.onclick=()=>this.game.perfOverlay.exportReport();section.append(health,report);}
        }
        document.getElementById('settings-back').onclick=()=>{this.cancelCapture();this.ui.closeSettings();};document.getElementById('settings-reset').onclick=()=>{this.cancelCapture();this.game.inputManager.setupDefaultBindings();this.ui.saveStoredSettings(normalizeSettings());this.ui.applyStoredSettings();this.populate();this.ui.showNotification('Settings and bindings reset. Vsync changes may require restart.','info');};this.show(this.category);
    }
    show(category){this.cancelCapture();this.category=category;for(const section of document.querySelectorAll('#settings-menu section[data-category]'))section.hidden=section.dataset.category!==category;for(const b of document.querySelectorAll('.settings-tabs button'))b.setAttribute('aria-pressed',String(b.textContent===category));}
    populate(){const s=this.ui.getStoredSettings();for(const f of SETTINGS_FIELDS){const el=document.getElementById(f.id);if(f.type==='boolean')el.checked=s[f.key];else el.value=s[f.key];if(f.type==='range')document.getElementById(f.id+'-val').textContent=s[f.key]+(f.unit||'');el.disabled=!!f.desktop&&!window.darkRainDesktop?.display;}
        document.getElementById('set-resolution').disabled=!window.darkRainDesktop?.display||s.fullscreen;document.getElementById('set-shadow-size').disabled=!s.shadows;for(const key of ['bloom','aa','grain','vignette','chroma'])document.getElementById(SETTINGS_FIELDS.find(f=>f.key===key).id).disabled=!s.post;
        if(!window.darkRainDesktop?.display)document.getElementById('settings-display-status').textContent='Window resolution and Vsync are managed by your browser.';const restart=document.getElementById('settings-restart');if(this.ui.displayState)restart.hidden=!this.ui.displayState.restartRequired;this.renderBindings(document.getElementById('settings-bindings'));
    }
    read(){const s=this.ui.getStoredSettings();for(const f of SETTINGS_FIELDS){const el=document.getElementById(f.id);s[f.key]=f.type==='boolean'?el.checked:f.type==='range'||typeof f.defaultValue==='number'?Number(el.value):el.value;}s.bindings=this.game.inputManager.getBindings();return normalizeSettings(s);}
    change(field){let s=this.read();if(field.key==='quality')s=applyPreset(s,s.quality);this.ui.saveStoredSettings(s);this.ui._applySettingsObject(s);this.populate();}
    renderBindings(host){if(!host)return;host.replaceChildren();for(const [action,name]of Object.entries(ACTIONS)){const row=document.createElement('div');row.className='control-row';const label=document.createElement('span');label.textContent=name;row.append(label);const keys=this.game.inputManager.bindings.get(action)||[];for(let slot=0;slot<2;slot++){const button=document.createElement('button');button.className='key-badge';button.setAttribute('aria-label',name+' binding '+(slot+1));button.textContent=keys[slot]?this.ui.formatKeyCode(keys[slot]):'Unbound';button.onclick=()=>this.capture(action,slot,host);row.append(button);if(keys[slot]){const clear=document.createElement('button');clear.className='binding-clear';clear.textContent='×';clear.setAttribute('aria-label','Clear '+name+' binding '+(slot+1));clear.onclick=()=>this.assign(action,slot,null,host);row.append(clear);}}host.append(row);}}
    assign(action,slot,code,host){if(code)code=parseBinding(code)?.code||code;const manager=this.game.inputManager,keys=[...(manager.bindings.get(action)||[])];if(code){if(!validBinding(code)||code==='Escape'&&action!=='pause')return 'That key is reserved.';for(const [other,bound]of manager.bindings)if(other!==action&&Object.hasOwn(ACTIONS,other)&&bound.includes(code))return 'Already assigned to '+ACTIONS[other]+'. Clear that binding first.';keys[slot]=parseBinding(code).code;}else keys.splice(slot,1);const filtered=keys.filter(Boolean);if(action==='pause'&&!filtered.length)return 'Keep at least one Pause binding.';manager.rebind(action,[...new Set(filtered)]);const s=this.ui.getStoredSettings();s.bindings=manager.getBindings();this.ui.saveStoredSettings(s);manager.clearHeldInput();this.renderBindings(host);this.ui.populateControlsList?.();return null;}
    capture(action,slot,host){this.cancelCapture();const status=document.getElementById('binding-status');if(status)status.textContent='Press a key or mouse button for '+ACTIONS[action]+'. Hold modifiers for a combination; Esc cancels.';
        this.captureListener=e=>{e.preventDefault();e.stopImmediatePropagation();if(e.type==='keydown'&&e.repeat)return;if(e.code==='Escape'){this.cancelCapture();if(status)status.textContent='Binding unchanged.';return;}
            const modifier=/^(Control|Alt|Shift|Meta)(Left|Right)$/.test(e.code);if(modifier&&e.type==='keydown'){this.pendingModifier=e.code;return;}if(e.type==='keyup'&&!modifier)return;
            const code=modifier?this.pendingModifier:eventBinding(e);if(!code)return;const error=this.assign(action,slot,code,host);if(error){if(status)status.textContent=error;return;}this.cancelCapture();if(status)status.textContent='Binding saved.';};
        for(const type of ['keydown','keyup','mousedown'])document.addEventListener(type,this.captureListener,true);
    }
    cancelCapture(){if(this.captureListener){for(const type of ['keydown','keyup','mousedown'])document.removeEventListener(type,this.captureListener,true);this.captureListener=null;this.pendingModifier=null;}}
    dispose(){this.cancelCapture();document.removeEventListener('keydown',this.backListener);}
    async restart(){try{if(this.game.gameState==='playing'&&!await this.game.saveSystem.saveGame('settings_restart'))throw Error('Save failed');await window.darkRainDesktop.display.restart(this.game.gameState==='playing');}catch{this.ui.showNotification('Restart cancelled because your progress could not be saved.','danger');}}
}
