import * as THREE from 'three';import {StorageInstancedBufferAttribute,PointsNodeMaterial} from 'three/webgpu';import * as N from 'three/tsl';
/** Local rain volume. Terrain/roof sheltering is a separate, still-required mask. */
export function createComputeRain(renderer,texture,capacity=20000){
 const initial=new Float32Array(capacity*3);for(let i=0;i<capacity;i++){initial[i*3]=(i*73%997)/997*100-50;initial[i*3+1]=(i*37%991)/991*50;initial[i*3+2]=(i*47%983)/983*100-50;}
 const attribute=new StorageInstancedBufferAttribute(initial,3),positions=N.storage(attribute,'vec3',capacity),dt=N.uniform(0),center=N.uniform(new THREE.Vector3()),intensity=N.uniform(0),wind=N.uniform(new THREE.Vector3()),active=N.uniform(capacity,'uint');
 const compute=N.Fn(()=>{N.If(N.instanceIndex.lessThan(active),()=>{const p=positions.element(N.instanceIndex);p.y.subAssign(dt.mul(intensity).mul(20).mul(N.hash(N.instanceIndex).mul(.5).add(.5)));p.xz.addAssign(wind.xz.mul(dt));p.x.assign(p.x.sub(center.x).add(50).mod(100).add(center.x).sub(50));p.z.assign(p.z.sub(center.z).add(50).mod(100).add(center.z).sub(50));N.If(p.y.lessThan(center.y.sub(5)),()=>{p.y.assign(center.y.add(45));});});})().compute(capacity);
 const material=new PointsNodeMaterial({map:texture,color:0xbfd4e6,size:.55,transparent:true,opacity:.6,depthWrite:false,blending:THREE.AdditiveBlending});material.positionNode=positions.element(N.instanceIndex);
 const mesh=new THREE.Sprite(material);mesh.geometry=mesh.geometry.clone();mesh.geometry.setAttribute('rainPosition',attribute);mesh.count=capacity;mesh.visible=false;mesh.frustumCulled=false;mesh.raycast=()=>{};mesh.userData.prewarm=true;mesh.name='compute-rain';
 let initialized=false;const ready=renderer.compileComputeAsync(compute).then(()=>{initialized=true;});ready.catch(error=>console.error('Dark Rain rain compute warmup failed',error));
 return {mesh,ready,setCount(count){active.value=Math.max(0,Math.min(capacity,Math.floor(count)));mesh.count=active.value;},update(seconds,position,rain,windDirection,windStrength){if(!initialized)return;dt.value=Math.min(.1,Math.max(0,seconds));center.value.copy(position);intensity.value=rain;wind.value.copy(windDirection).multiplyScalar(windStrength*5);material.opacity=.3+rain*.4;renderer.compute(compute);},dispose(){compute.dispose();mesh.removeFromParent();mesh.geometry.dispose();material.dispose();}};
}
