import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {tunnelLandscape} from './TunnelLandscape.js';
import * as THREE from 'three';
import RAPIER from '@dimforge/rapier3d-compat';
import {getProceduralSet} from './ProceduralTextures.js';
import {fractureExisting} from '../systems/destruction/SecondaryFracture.js';
import {addDestructibleWalls} from './DestructibleWalls.js';
export const TUNNEL_ORIGIN={x:1200,y:0,z:1200};
export const TUNNEL_RADIUS=6;
export function buildTutorialTunnel(world){
 const o=TUNNEL_ORIGIN,set=typeof document==='undefined'?{}:getProceduralSet('concrete'),roadSet=typeof document==='undefined'?{}:getProceduralSet('asphalt');world.game.lootSystem?.clear();
 const concrete=new THREE.MeshStandardMaterial({color:0x686d66,map:set.map||null,normalMap:set.normalMap||null,roughness:.96,side:THREE.DoubleSide}),steel=new THREE.MeshStandardMaterial({color:0x343d38,metalness:.55,roughness:.83}),rust=new THREE.MeshStandardMaterial({color:0x67503b,metalness:.4,roughness:.9}),asphalt=new THREE.MeshStandardMaterial({color:0x73756e,map:roadSet.map||null,bumpMap:roadSet.bumpMap||null,bumpScale:.035,roughness:.98});
 const add=(geometry,p,material=concrete,collidable=true)=>{const mesh=new THREE.Mesh(geometry,material);mesh.position.set(o.x+p[0],p[1],o.z+p[2]);mesh.castShadow=mesh.receiveShadow=true;mesh.userData.isCollidable=collidable;world.scene.add(mesh);world._cityObjects.push(mesh);if(collidable)world.colliders.push(mesh);return mesh;};
 const structuralParts=new Map(),structuralVisuals=[];
 const box=(size,p,material=concrete,collidable=true)=>{const g=new THREE.BoxGeometry(...size),uv=g.attributes.uv,n=g.attributes.normal;for(let i=0;i<uv.count;i++){const u=Math.abs(n.getX(i))>.5?size[2]:size[0],v=Math.abs(n.getY(i))>.5?size[2]:size[1];uv.setXY(i,uv.getX(i)*u/1.8,uv.getY(i)*v/1.8);}const mesh=add(g,p,material,collidable);if(collidable&&p[1]>.2){let list=structuralParts.get(material);if(!list){list=[];structuralParts.set(material,list);}list.push({size,position:p,density:material===concrete?2100:3000,health:material===concrete?68:120,capacity:2000000});structuralVisuals.push(mesh);}return mesh;};
 for(let bay=0;bay<11;bay++){const z=3-bay*5,positions=[],uvs=[],sideRoom=bay===4?1:bay===7?-1:0;
  for(let i=0;i<48;i++){if(sideRoom===1&&i<8||sideRoom===-1&&i>=40)continue;const a=i*Math.PI/48,b=(i+1)*Math.PI/48,r=6,v=[[r*Math.cos(a),r*Math.sin(a),-2.5],[r*Math.cos(a),r*Math.sin(a),2.5],[r*Math.cos(b),r*Math.sin(b),2.5],[r*Math.cos(b),r*Math.sin(b),-2.5]];for(const j of [0,1,2,0,2,3]){positions.push(...v[j]);uvs.push((j<2?a:b)*r/1.8,(j===1||j===2?5:0)/1.8);}}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.computeVertexNormals();const lining=add(g,[0,0,z],concrete,false);lining.userData.type='tunnel-arch';structuralVisuals.push(lining);
  let list=structuralParts.get(concrete);if(!list){list=[];structuralParts.set(concrete,list);}for(let i=0;i<32;i++){if(sideRoom===1&&i<6||sideRoom===-1&&i>=26)continue;const a=(i+.5)*Math.PI/32;for(const dz of [-1.25,1.25])list.push({size:[2*6*Math.sin(Math.PI/64),.18,2.5],position:[6*Math.cos(a),6*Math.sin(a),z+dz],quaternion:new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),a-Math.PI/2),anchor:i===0||i===31,density:2100,health:68,capacity:2000000});}
  for(const x of [-4.7,4.7])box([.12,.12,5],[x,3.35,z],rust,false);for(const x of [-5.25,5.25])box([.35,.10,5],[x,.05,z],steel);
 }
 box([24,.3,184],[0,-.15,-58],asphalt);const paint=new THREE.MeshStandardMaterial({color:0x8a8468,roughness:1});for(let i=0;i<10;i++)box([.1,.006,2],[0,.004,-i*5],paint,false);
 box([3.8,.42,.65],[0,1.45,-14],rust);for(const x of [-1.95,1.95])box([.15,1.65,.2],[x,.825,-14],steel);
 for(const [side,z]of [[1,-17],[-1,-32]]){const x=side*8;box([4.6,.25,5],[x,-.125,z]);box([.3,3,5],[side*10.3,1.5,z]);for(const dz of [-2.6,2.6])box([4.8,3,.3],[x,1.5,z+dz]);box([5.7,.25,5.5],[x,3.12,z]);for(const y of [.6,1.35,2.1])box([.8,.08,3],[side*9.6,y,z],rust);box([.14,2.4,1.4],[side*5.8,1.2,z-1.9],rust);}
 for(const side of [-1,1])box([.5,2.8,5],[side*6.2,1.4,-50],concrete);add(new THREE.TorusGeometry(6.2,.32,8,40,Math.PI),[0,0,-49.6]);tunnelLandscape(add);
 const light=(color,intensity,p,distance)=>{const l=new THREE.PointLight(color,intensity,distance,2);l.position.set(o.x+p[0],p[1],o.z+p[2]);world.scene.add(l);world._cityObjects.push(l);};light(0xc69b55,3,[2.5,1.2,-2],9);light(0x77968b,1,[8,2,-17],7);light(0xc89755,1,[-8,2,-32],7);light(0xdce5d7,65,[0,4,-55],24);
 const plate=(text,p)=>{if(typeof document==='undefined')return;const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#293730';ctx.fillRect(0,0,512,128);ctx.fillStyle='#cdc5a8';ctx.font='bold 23px monospace';ctx.textAlign='center';ctx.fillText(text,256,70);const texture=new THREE.CanvasTexture(c);texture.colorSpace=THREE.SRGBColorSpace;add(new THREE.PlaneGeometry(2.8,.7),p,new THREE.MeshStandardMaterial({map:texture,roughness:1}),false);for(const x of [-1,1]){const roof=Math.sqrt(Math.max(0,36-(p[0]+x)*(p[0]+x))),length=Math.max(.08,roof-p[1]-.35);box([.018,length,.018],[p[0]+x,p[1]+.35+length/2,p[2]],steel,false);}};
 plate('EMERGENCY SUPPLIES / SEARCH',[2.5,1.8,-3]);plate('LOW CLEARANCE',[0,2,-13.6]);plate('MAINTENANCE / FIRST AID',[4.6,2.5,-17]);plate('SURFACE ACCESS / ATLANTA',[0,3.7,-48]);
 world.tutorialContainers=[];const loot=world.game.lootSystem;if(loot){const stash=(type,x,z,items,supportY=0)=>world.tutorialContainers.push(loot.spawnContainer(type,o.x+x,o.z+z,{supportY,items}));stash('supply_crate',2.5,-2,[{id:'flashlight',count:1},{id:'weapon_crowbar',count:1}]);stash('med_crate',9.6,-17,[{id:'bandage',count:4},{id:'medkit_small',count:1}],.64);stash('supply_crate',-9.6,-32,[{id:'weapon_pm_pistol',count:1},{id:'ammo_pistol',count:24},{id:'water_bottle',count:1},{id:'frag_grenade',count:2},{id:'weapon_fireaxe',count:1}],.64);stash('stash',3.8,-37,[{id:'detector',count:1},{id:'canned_food',count:1}]);}
 const practice=box([.35,.15,.25],[9.6,.715,-18],new THREE.MeshStandardMaterial({color:0x67443e}),false);practice.userData.isInteractive=true;practice.userData.promptText='Practice first aid (small cut: 8 damage)';practice.userData.interactable={onInteract:()=>world.game.tutorialSystem?.practiceFirstAid()};
 world.tutorialDefinition={origin:o,radius:6,rooms:2,props:[]};
 const timberSet=typeof document==='undefined'?{}:getProceduralSet('wood'),timber=new THREE.MeshStandardMaterial({color:0x777d6c,map:timberSet.map||null,normalMap:timberSet.normalMap||null,roughness:.97});
 for(const key of ['map','normalMap'])if(timber[key]){timber[key]=timber[key].clone();timber[key].center.set(.5,.5);timber[key].rotation=Math.PI/2;timber[key].needsUpdate=true;}
 const fence=new THREE.Group();fence.position.set(o.x,0,o.z-29);fence.updateMatrixWorld(true);const boards=[];
 for(let i=0;i<25;i++){const x=(i-12)*.43,height=3.2+(i%3)*.09;boards.push({size:[.415,height,.03],position:[x,height/2+.03,0],anchor:false,density:580,health:30,capacity:90000});}
 for(const x of [-5.3,-2.65,0,2.65,5.3])boards.push({size:[.16,3.65,.17],position:[x,1.825,-.13],anchor:true,density:650,health:65,capacity:180000});
 for(const y of [.65,2.5])for(let i=0;i<4;i++)boards.push({size:[2.65,.14,.13],position:[-3.975+i*2.65,y,-.13],anchor:false,density:600,health:40,capacity:110000});
 const barricade=addDestructibleWalls(world,fence,boards,timber);barricade.name='nailed-timber-barricade';barricade.userData.tutorialBarricade=true;
 // Uneven board heights and offset posts retain a handmade silhouette.

 // A deep landslide reaches the crown. Static retaining faces prevent the rear
 // pile escaping behind the player, while the visible stones remain physical.
 const structure=new THREE.Group();structure.position.set(o.x,0,o.z);structure.updateMatrixWorld(true);let surface=0;for(const [material,sections]of structuralParts){const mesh=addDestructibleWalls(world,structure,sections,material);mesh.userData.glassId+=':tunnel:'+surface++;mesh.name='destructible-tunnel-lining';}
 for(const mesh of structuralVisuals){mesh.visible=false;mesh.removeFromParent();world.colliders=world.colliders.filter(c=>c!==mesh);}
 const cliff=add(new THREE.IcosahedronGeometry(9,2),[0,0,8],concrete);cliff.scale.set(1,1,.3);for(let row=0;row<3;row++){const y=.92+row*1.8,half=Math.sqrt(Math.max(0,36-(y+.9)*(y+.9)))-1;for(let x=-Math.floor(half/1.95)*1.95;x<=half;x+=1.95)for(let depth=0;depth<2;depth++)world.tutorialDefinition.props.push({id:`tutorial-rubble:${row}:${x.toFixed(2)}:${depth}`,position:[o.x+x,y,o.z+2.5+depth*1.9],size:[2.0,1.85,1.9],mass:450,rock:true});}world.tutorialDefinition.props.push({id:"tutorial-rubble:crown",position:[o.x,5.5,o.z+3.6],size:[2.1,.8,1.9],mass:450,rock:true});
 world.tutorialDefinition.cars=[{id:'tunnel-wreck:0',position:[o.x-3,.75,o.z-9],yaw:.14,color:0x454e48},{id:'tunnel-wreck:1',position:[o.x+3,.75,o.z-24],yaw:-.3,color:0x675a48},{id:'tunnel-wreck:2',position:[o.x-3,.75,o.z-41],yaw:.38,color:0x505762}];
 for(let i=0;i<32;i++){const side=i%2?1:-1;world.tutorialDefinition.props.push({id:'tunnel-scrap:'+i,position:[o.x+side*(3.8+(i%5)*.23),.06,o.z-4-i*1.3],size:[.3+(i%4)*.13,.045,.15+(i%3)*.2],mass:1.5,health:15,scrap:true,yaw:i*2.399});}
}
export function spawnTutorialProps(physics){
 const world=physics.game.worldManager,stone=typeof document==='undefined'?{}:getProceduralSet('rubble');for(const p of world.tutorialDefinition?.props||[]){const size=new THREE.Vector3(...p.size),mesh=new THREE.Mesh(p.rock?new THREE.IcosahedronGeometry(1,1):new THREE.BoxGeometry(...p.size),new THREE.MeshStandardMaterial({color:p.rock?0x77796d:0x69513b,map:p.rock?stone.map||null:null,bumpMap:p.rock?stone.bumpMap||null:null,bumpScale:.09,roughness:.97}));mesh.position.fromArray(p.position);mesh.rotation.y=p.yaw||0;if(p.rock){const vertices=mesh.geometry.attributes.position;for(let i=0;i<vertices.count;i++){const x=vertices.getX(i),y=vertices.getY(i),z=vertices.getZ(i),shape=1+.11*Math.sin(x*7+y*5+z*3+p.position[0]);vertices.setXYZ(i,x*shape,y*shape,z*shape);}mesh.geometry.computeVertexNormals();}if(p.rock)mesh.scale.copy(size).multiplyScalar(.5);mesh.castShadow=mesh.receiveShadow=true;physics.game.scene.add(mesh);physics.addBody(mesh,p.rock?size.clone().multiplyScalar(.5):size,{mass:p.mass,id:p.id,health:p.health??(p.rock?180:60),convex:!!p.rock,breakable:p.rock?{material:'concrete',health:180,impactEnergyJ:4000,fragments:fractureExisting(mesh.geometry,mesh.scale,6)}:undefined});}
 for(const car of world.tutorialDefinition?.cars||[]){const group=new THREE.Group();group.position.fromArray(car.position);group.rotation.y=car.yaw;const body=new THREE.MeshStandardMaterial({color:car.color,metalness:.4,roughness:.86}),rubber=new THREE.MeshStandardMaterial({color:0x222522,roughness:.98}),shapes=[],positions=[],rotations=[];
  const part=(size,p,m=body)=>{const mesh=new THREE.Mesh(new RoundedBoxGeometry(...size,2,Math.min(.10,...size.map(v=>v*.3))),m);mesh.position.set(p[0],p[1]-.75,p[2]);mesh.castShadow=mesh.receiveShadow=true;group.add(mesh);shapes.push(new RAPIER.Cuboid(size[0]/2,size[1]/2,size[2]/2));positions.push(mesh.position);rotations.push(mesh.quaternion);};
  part([1.8,.55,4],[0,.68,0]);part([1.65,.12,1.8],[0,1.65,-.1]);part([1.75,.08,1.1],[0,.97,1.3]);for(const x of [-.78,.78])for(const z of [-.85,.65])part([.10,.7,.1],[x,1.3,z]);
  for(const x of [-.9,.9])for(const z of [-1.3,1.3]){const wheel=new THREE.Mesh(new THREE.CylinderGeometry(.34,.34,.23,12),rubber);wheel.rotation.z=Math.PI/2;wheel.position.set(x,.35-.75,z);wheel.castShadow=wheel.receiveShadow=true;group.add(wheel);shapes.push(new RAPIER.Cuboid(.34,.115,.34));positions.push(wheel.position);rotations.push(wheel.quaternion);}
  physics.game.scene.add(group);physics.addBody(group,new THREE.Vector3(1,1,1),{id:car.id,mass:1150,collider:RAPIER.ColliderDesc.compound(shapes,positions,rotations,0)});
 }
}
