const {app,BrowserWindow}=require('electron'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'work','stress-profile');fs.mkdirSync(dir,{recursive:true});app.setPath('userData',path.join(dir,'profile-'+Date.now()));app.commandLine.appendSwitch('disable-renderer-backgrounding');const delay=ms=>new Promise(r=>setTimeout(r,ms)),errors=[];let win,finished=false;const report={schema:1,time:new Date().toISOString(),status:'starting',requestedPreset:process.argv.includes('--low')?'low':'default',requestedBackend:process.argv.includes('--webgl')?'WebGL2':'WebGPU primary',scope:'full configured city; real gameplay systems; hero collapse mid-emission',metric:'serial simulation + render + GPU completion, not click-to-photon or presentation pacing'};report.processMemory=[];const file=path.join(dir,'latest.json');const write=()=>fs.writeFileSync(file,JSON.stringify(report,null,2));write();const deadline=setTimeout(()=>{report.status='timeout';report.errors=errors;write();console.error('Stress profile timed out');app.exit(1);},150000);
app.on('web-contents-created',(_,wc)=>{wc.on('console-message',e=>{if(e.message.startsWith('PROFILE'))console.log(e.message);if(e.level==='error')errors.push(e.message);});wc.on('render-process-gone',(_,details)=>{report.status='renderer-failed';report.rendererFailure=details;report.errors=errors;write();app.exit(1);});});
let memoryTimer;app.whenReady().then(async()=>{try{memoryTimer=setInterval(()=>{try{const processes=app.getAppMetrics().map(p=>({type:p.type,pid:p.pid,privateKiB:p.memory.privateBytes??null,workingSetKiB:p.memory.workingSetSize}));report.processMemory.push({time:Date.now(),processes});if(report.processMemory.length>150)report.processMemory.shift();}catch{}},500);report.gpu=await app.getGPUInfo('basic');write();await import('../release/win-unpacked/resources/app.asar/out/main/index.js');await delay(100);win=BrowserWindow.getAllWindows()[0];const boot=async()=>{for(let i=0;i<400;i++){if(await win.webContents.executeJavaScript('!!window.__drBooted'))return;await delay(100);}throw Error('Main menu did not boot');};await boot();if(process.argv.includes('--webgl')){await win.loadFile(path.join(root,'release/win-unpacked/resources/app.asar/out/renderer/index.html'),{query:{backend:'webgl'}});await boot();}
 if(process.argv.includes('--low'))await win.webContents.executeJavaScript(`const settings={...game.uiManager.getStoredSettings(),quality:'low',renderScale:50,shadows:false,bloom:false,aa:false,reflectionQuality:'low',particleQuality:'low',vegetationDetail:false,autoQuality:false};localStorage.setItem('darkrain_settings',JSON.stringify(settings));game.uiManager.applyStoredSettings();void 0;`);
 await win.webContents.executeJavaScript(`const m=game.startup.measure.bind(game.startup);game.startup.measure=async(n,f)=>{console.log('PROFILE start '+n);const result=await m(n,f);console.log('PROFILE done '+n);return result;};game._tutorialRequested=false;game.uiManager.hideMainMenu();window.stressStart=game.beginSession(false);void 0;`);await win.webContents.executeJavaScript('stressStart.then(()=>true)');
 report.data=await win.webContents.executeJavaScript(`(async()=>{const g=game;if(g.gameState!=='playing'||!g.physicsSystem?.playerBody)throw Error('World failed to enter playable state');g.stop();g.uiManager.hideAllMenus();g.isPaused=false;g.player.godMode=true;g.settings.autoQuality=false;g.saveSystem.update=()=>{};g.inputManager.clearHeldInput();const percentile=(a,p)=>{const b=a.slice().sort((x,y)=>x-y);return b[Math.min(b.length-1,Math.floor(b.length*p))];};const summary=a=>({mean:a.reduce((s,v)=>s+v,0)/a.length,p95:percentile(a,.95),p99:percentile(a,.99),max:Math.max(...a)});const finish=async()=>{if(g.renderer._isDeviceLost||g.gameState!=='playing')throw Error('Graphics/gameplay state lost during stress sample');const d=g.renderer.backend.device;if(d)await d.queue.onSubmittedWorkDone();else{const gl=g.renderer.getContext();if(!gl||gl.isContextLost())throw Error('Graphics context lost');gl.finish();}};
 const cases=[];for(const scale of [1,.75,.5]){g._autoQuality.effRenderScale=scale;g._applyRenderScale();const f=g.physicsSystem.spawnFixture(),o=f.origin;g.player.position.set(o.x,o.y+.1,o.z+22);g.player.cameraYaw=0;g.player.cameraPitch=0;g.player.updateCamera(0);g.emissionSystem.phase='dormant';g.emissionSystem.setPhase('emission');g.emissionSystem.phaseTime=0;
 for(let i=0;i<12;i++){g.update(1/60);g.fixedUpdate(1/60);g.renderer._nodes.nodeFrame.update();g.render(true);await finish();}const total=[],cpu=[],render=[],gpu=[],systems={},rows=[];let airborne=0,failures=0,maxDraw=0,maxTriangles=0;
 for(let i=0;i<120;i++){const start=performance.now();g.perfOverlay.systemTimes.clear();if(i===0)f.demolishAllSupports();g.update(1/60);g.fixedUpdate(1/60);const renderStart=performance.now();g.renderer._nodes.nodeFrame.update();g.render(true);const submitted=performance.now();await finish();const end=performance.now();total.push(end-start);cpu.push(renderStart-start);render.push(submitted-renderStart);gpu.push(end-submitted);const active=f.nodes.reduce((n,b)=>n+(b.alive&&b.loose&&!b.body.isSleeping()?1:0),0);airborne=Math.max(airborne,active);failures=Math.max(failures,f.failedJointIds.size);const info=g.renderer.info.render;maxDraw=Math.max(maxDraw,info.drawCalls??info.calls??0);maxTriangles=Math.max(maxTriangles,info.triangles||0);for(const [name,cost]of g.perfOverlay.systemTimes){(systems[name]||=[]).push(cost);}rows.push([i,end-start,renderStart-start,submitted-renderStart,end-submitted,active]);if(i%30===0){console.log('PROFILE scale '+scale+' frame '+i);await new Promise(r=>setTimeout(r,0));}}
 if(!airborne||!failures||g.emissionSystem.phase!=='emission'||!g.alifeSystem||!g.anomalySystem.anomalies.size||!maxDraw)throw Error('Stress workload incomplete');cases.push({scale,frames:120,total:summary(total),simulation:summary(cpu),renderSubmission:summary(render),gpuWait:summary(gpu),systems:Object.fromEntries(Object.entries(systems).map(([k,v])=>[k,summary(v)])),airborneBodies:airborne,failedJoints:failures,maxDrawCalls:maxDraw,maxTriangles,anomalies:g.anomalySystem.anomalies.size,alifeParties:g.alifeSystem.parties.size,rows});}
 const gl=g.renderer.backendName==='WebGL2'?g.renderer.getContext():null,debug=gl?.getExtension('WEBGL_debug_renderer_info');return {adapter:debug?gl.getParameter(debug.UNMASKED_RENDERER_WEBGL):g.renderer.backend.adapter?.info||null,backend:g.renderer.backendName,resolution:[innerWidth,innerHeight],city:g.worldManager.city,quality:g.settings.quality,scalerDisabledForControlledComparison:true,cases};})()`);
 if(errors.length)throw Error(errors.join('\n'));report.status='measured';report.errors=errors;const {compareStressProfile}=await import('../src/core/diagnostics/StressComparison.js');report.comparison=compareStressProfile(report);write();console.log(JSON.stringify({status:report.status,backend:report.data.backend,cases:report.data.cases.map(c=>({scale:c.scale,total:c.total,simulation:c.simulation,renderSubmission:c.renderSubmission,gpuWait:c.gpuWait,draws:c.maxDrawCalls,airborne:c.airborneBodies}))},null,2));finished=true;app.exit(0);
 }catch(e){report.status='failed';report.error=e.message;report.errors=errors;write();console.error(e);app.exit(1);}finally{clearInterval(memoryTimer);clearTimeout(deadline);win?.destroy();}});app.on('before-quit',()=>{if(!finished)process.exitCode=1;});
