const bits={Ctrl:1,Alt:2,Shift:4,Meta:8};
const key=/^(Key[A-Z]|Digit[0-9]|F([1-9]|1[0-9]|2[0-4])|Arrow(Up|Down|Left|Right)|Space|Tab|Escape|Enter|Backspace|Shift(Left|Right)|Control(Left|Right)|Alt(Left|Right)|Meta(Left|Right)|Mouse[0-4]|Wheel(Up|Down)|Numpad([0-9]|Add|Subtract|Multiply|Divide|Decimal|Enter)|CapsLock|Insert|Delete|Home|End|PageUp|PageDown|Bracket(Left|Right)|Semicolon|Quote|Comma|Period|Slash|Backslash|Minus|Equal|Backquote)$/;
export function parseBinding(value){if(typeof value!=='string')return null;const parts=value.split('+'),base=parts.pop();if(!key.test(base))return null;let mask=0;for(const modifier of parts){if(!Object.hasOwn(bits,modifier))return null;mask|=bits[modifier];}const prefixes=Object.keys(bits).filter(m=>mask&bits[m]);return {base,mask,specificity:prefixes.length,code:[...prefixes,base].join('+')};}
export function eventMask(event){return (event.ctrlKey?1:0)|(event.altKey?2:0)|(event.shiftKey?4:0)|(event.metaKey?8:0);}
export function eventBinding(event){const base=event.type==='mousedown'?'Mouse'+event.button:event.code;if(/^(Control|Shift|Alt|Meta)(Left|Right)$/.test(base))return base;const prefixes=Object.keys(bits).filter(m=>eventMask(event)&bits[m]);return [...prefixes,base].join('+');}
export function compileBindings(bindings){const byAction=new Map(),byBase=new Map();for(const [action,values]of bindings){const entries=values.map(parseBinding).filter(Boolean);byAction.set(action,entries);for(const entry of entries){entry.action=action;if(!byBase.has(entry.base))byBase.set(entry.base,[]);byBase.get(entry.base).push(entry);}}return {byAction,byBase};}
export function modifierBit(code){return code?.startsWith('Control')?1:code?.startsWith('Alt')?2:code?.startsWith('Shift')?4:code?.startsWith('Meta')?8:0;}
export function winners(compiled,base,mask){const entries=compiled.byBase.get(base)||[],effective=mask&~modifierBit(base),exact=entries.filter(b=>b.mask!==0&&b.mask===effective);return exact.length?exact:entries.filter(b=>b.mask===0);}
export function bindingMatches(compiled,binding,mask){const effective=mask&~modifierBit(binding.base);if(binding.mask!==0)return binding.mask===effective;for(const other of compiled.byBase.get(binding.base)||[])if(other.mask!==0&&other.mask===effective)return false;return true;}
